### ISSUE TITLE
Delayed session displaying in desktop client v2.0.0

### ISSUE THREAD

**Issue by yongzhang** [hashicorp/boundary-ui#2130] opened 2024-02-06 06:57 UTC
**Describe the bug**
Hi, team

I observe a very long delayed session list displaying in desktop client v2.0.0 (tested in windows).

**To Reproduce**
1. Login to desktop client and connect any target
2. Go to "Sessions", see:
![image](https://github.com/hashicorp/boundary-ui/assets/15604715/1031057e-9741-406d-ac4f-ed0fdf7addd7)
3. But if go to web UI, see sessions already there:
![image](https://github.com/hashicorp/boundary-ui/assets/15604715/92e11bf2-4359-4c59-a83b-5b15afacce51)
4. After a long time (3+ minutes), sessions are displaying
![image](https://github.com/hashicorp/boundary-ui/assets/15604715/ef5b701b-217c-4c1c-9c0c-bbc5b2b63d26)

What could be wrong here?

**Expected behavior**

**Additional context**

**Comment by lisbet-alvarez** [comment] 2024-02-06 18:03
Hello @yongzhang thank you for using Boundary,
Can you try connecting to the same target again, after connecting to the target open up a terminal and send a screenshot of what the output for this cli command `boundary daemon status` is?

**Comment by yongzhang** [comment] 2024-02-07 00:47
> Hello @yongzhang thank you for using Boundary, Can you try connecting to the same target again, after connecting to the target open up a terminal and send a screenshot of what the output for this cli command `boundary daemon status` is?

I'm using Windows laptop, is this only available for osx and linux?

**Comment by yongzhang** [comment] 2024-02-07 00:58
But before reproduce the issue, I see some weird staff, I actually terminated the session for a long time, but got output like this:
```
Status:
  Domain Socket:       C:\Users\yongzhang\.boundary\socket\daemon.sock
  Log Location:        C:\Users\yongzhang\.boundary\cache.log
  Uptime:              9m34s
  User Count:          1
  Version:             Boundary v0.15.0
  (18f863514ee5c4cfa6e0cb0c497049f1b5104511)

  User:
    Address:                        my-controll-url
    AuthToken Count:                1
    Id:                             u_Ws4koCpYi5
    Search Support:                 Supported
    Since Search Support Check:     51s
    AuthToken:
      Id:                      at_gJwkbnpZAS
    Target:
      Count:                     2
      Since Initial Fetch:       9m33s
      Since Last Refresh:        51s
    Session:
      Count:                     1
      Since Initial Fetch:       4m51s
      Since Last Refresh:        51s
```

I see session count is 1, this should be incorrect?

![image](https://github.com/hashicorp/boundary-ui/assets/15604715/58a7799b-79f3-439b-b79d-15a1521a163a)

**Comment by lisbet-alvarez** [comment] 2024-02-07 01:34
The session count being 1 in the output is correct because the count includes sessions with terminated status. In fact the desktop client should also give users the ability to display terminated sessions. Like in the image below. (The session status can be confirmed by accessing your boundary binary, authenticating with the same user used to authenticate to the desktop client and using the cmd `boundary search -resource=sessions`.)
![image](https://github.com/hashicorp/boundary-ui/assets/107949262/f83e054c-277b-43a7-a9fe-d503e026e987)

There seems to be an issue here because in the screenshot the desktop client is not displaying the terminated session. I haven't been able to reproduce this issue, so I have a few more questions: are you authenticating as the `admin` user, if not what grants strings does that particular user have assigned to them. Additionally, are you running a `boundary dev` instance or is the issue being observed while using a boundary hcp cluster instance?

**Comment by lisbet-alvarez** [comment] 2024-02-07 01:40
The session count being 1 in the output is correct because the count includes sessions with terminated status. In fact the desktop client should also give users the ability to display terminated sessions. Like in the image below. (The session status can be confirmed by accessing your boundary binary, authenticating with the same user used to authenticate to the desktop client and using the cmd `boundary.exe search -resource=sessions`.)
![image](https://github.com/hashicorp/boundary-ui/assets/107949262/f83e054c-277b-43a7-a9fe-d503e026e987)

There seems to be an issue here because in the screenshot the desktop client is not displaying the terminated session. I haven't been able to reproduce this issue, so I have a few more questions: are you authenticating as the `admin` user, if not what grants strings does that particular user have assigned to them. Additionally, are you running a `boundary dev` instance or is the issue being observed while using a boundary hcp cluster instance?

**Comment by yongzhang** [comment] 2024-02-07 05:54
Reproduce and check command output:

OS: Windows 11
Desktop Client: v2.0.0
Arch: Boundary controllers are in an ASG, there's an NLB listening on port 443(for API, do tls termination) and TCP port 9201 for worker registration. Workers are setup in private networks with NLB in front of them and export TCP port 9202 for client connection.

The issue happens on v2.0.0, it works very well on 1.7.x.

1. Login to org with Okta:
![image](https://github.com/hashicorp/boundary-ui/assets/15604715/75792a7b-96ea-4f9a-af35-3f31389e723c)

2. Connect to any target and confirm session id:
![image](https://github.com/hashicorp/boundary-ui/assets/15604715/b4426ed0-74cf-45c3-b278-cc2b5f897131)

3. Click "Sessions", see nothing there (No refresh button here so we can't refresh):
![image](https://github.com/hashicorp/boundary-ui/assets/15604715/8bab3dda-dcbc-40be-bbde-347fb40f877e)

4. Checkout boundary daemon status;
```
C:\Users\YongZhang>.\boundary daemon status

Status:
  Domain Socket:       C:\Users\yongzhang\.boundary\socket\daemon.sock
  Log Location:        C:\Users\yongzhang\.boundary\cache.log
  Uptime:              2m34s
  User Count:          1
  Version:             Boundary v0.15.0
  (18f863514ee5c4cfa6e0cb0c497049f1b5104511)

  User:
    Address:                        my-boundary-url
    AuthToken Count:                2
    Id:                             u_4vbBKEXRgE
    Search Support:                 Supported
    Since Search Support Check:     1m10s
    AuthToken:
      Id:                      at_YoXpOfTjVV
    AuthToken:
      Id:                      at_c4umDM65U1
    Target:
      Count:                     75
      Since Initial Fetch:       2m32s
      Since Last Refresh:        1m10s
    Session:
      Count:                   0
```
5. Login to web ui and check sessions, we can see the session:
![image](https://github.com/hashicorp/boundary-ui/assets/15604715/fb5a0013-065f-4913-81d2-3df5f4f8bf04)

**Comment by lisbet-alvarez** [comment] 2024-02-07 22:26
Thank you for your patience and for the details provided.
I was able to reproduce this issue, and the bug causing this was found. Please expect this fix in the next release. 

In regards to step #4 the status printed is correct, the reason the count is 0 is because the daemon cache by default is only refreshed every 5 mins (default value of the `refresh-interval` flag), or when a search request is made and the `max-search-staleness` time has been reached. For information on what each flag does and default values the `boundary daemon start -help` command can be used. In the meantime, the `-refresh-interval` flag can be modified to see updates sooner.

**Closed** 2024-02-13 19:44 UTC
Labels: triage
